### ISSUE TITLE
Bug about fteik3d

### ISSUE THREAD

**Issue by Liuyaguangzz** [Mark-Noble/FTeik-Eikonal-Solver#2]
Dear Dr.Noble

Thanks for sharing this package.

While using it, I noticed that there are some bugs in the 3D program.

When setting the source on the boundary of the 3D medium, it will return an incorrect result.

Such as I have a grid $501\times501\times501$, and I set the $dx=dy=dz=5$. I set 9 source point , list as:
|zsrc|xsrc|ysrc|
|-|-|-|
|0|0|0|
|0|0|0|
|0|0|0|
|0|0|0|
|0|0|0|

**Comment by Liuyaguangzz** [comment]
Dear Dr.Noble

Thanks for sharing this package.

While using it, I noticed that there are some bugs in the 3D program.

When setting the source on the boundary of the 3D medium, it will return an incorrect result.

Such as I have a grid $501\times501\times501$, and I set the $dx=dy=dz=5$. I set 9 source point , list as:

|zsrc|xsrc|ysrc|
|-|-|-|
|0|0|0|
|0|1250|0|
|0|2500|0|
|0|0|1250|
|0|1250|1250|
|0|2500|1250|
|0|0|2500|
|0|1250|2500|
|0|2500|2500|

For the first, second, fourth, and fifth source points, the maximum boundary point is not reached, and the results are normal. For example, the top slice of the three-dimensional travel time field corresponding to the second source point shown below

![微信截图_20231210210454](https://github.com/Mark-Noble/FTeik-Eikonal-Solver/assets/46919572/703684cd-331b-4572-842c-0e53c79a4f79)

But for the remaining source points reaching the maximum boundary, the calculated travel time field results are puzzling, such as the 3rd source point and the 8th source point shown below

3rd

![微信截图_20231210210738](https://github.com/Mark-Noble/FTeik-Eikonal-Solver/assets/46919572/7376a8b1-ed6b-4510-885d-9ddcbe0edc45)

8th
![微信截图_20231210210817](https://github.com/Mark-Noble/FTeik-Eikonal-Solver/assets/46919572/cd735590-3639-48e7-aa6d-a5658fededb2)

I haven't found the reason yet. I hope you can take a look at what the problem is or whether I made some low-level mistakes. Thank you.

**Comment by Mark-Noble** [comment]
Thank you very much for pointing out the problem. Sources placed on far side edge were creating problems.
I hope I have fixed it, modifications where done in the file fteik3d.f90. You'll need to download this routine and recompile code.
Hope the problem is solved. You are using Su ximage, you can also use xcontour to clearly visualize wavefronts.
A new version of the Eikonal, more accurate is under test and I hope to drop in Github very soon.

**Comment by Mark-Noble** [comment]
Please confirm if problem is fixed

**Comment by Liuyaguangzz** [comment]
Thank you very much for fixing this, and thank you for the recommended display tool xcontour.
I have test it, and the problem has been solved.
However, I still have a little confusion. When the source is at the boundary, the minimum value of the travel time field is not zero but 2.5e-7, but when the source is inside, the minimum value is zero, but this has nothing to do with it, it is just a small error.
Thank you very much!!!
